export {default as Home} from './Home/Home'
export {default as Register} from './Register/Register'
export {default as Login} from './Login/Login'
export {default as Profile} from './Profile/Profile'
export {default as ProfileDetail} from './Profile/ProfileDetail'
export {default as Cart} from './Cart/Cart'
export {default as ProductDetail} from './Product/ProductDetail'
