export default {
    HOME: require('../assets/icons/list.png'),
    PROFILE: require('../assets/icons/user.png'),
    DISCOVERY: require('../assets/icons/discovery.png'),
    LOGO_TRANS: require('../assets/icons/logo_trans.png'),
    LOGO_CIRCLE: require('../assets/icons/logo_circle.png'),
    USERNAME: require('../assets/icons/username.png'),
    PASSWORD: require('../assets/icons/password.png'),
    GO: require('../assets/icons/go.png'),
    SEE: require('../assets/icons/see.png'),
    UNSEE: require('../assets/icons/unsee.png'),
    FULLNAME: require('../assets/icons/fullname.png'),
    EMAIL: require('../assets/icons/email.png'),
    INFO: require('../assets/icons/information.png'),
    CHANGEPW: require('../assets/icons/change_pw.png'),
    NEW: require('../assets/icons/new.png'),
    ADDNEW: require('../assets/icons/addnew.png'),
    DELETE: require('../assets/icons/delete.png'),
    EDIT: require('../assets/icons/edit.png'),
    SEARCHING: require('../assets/icons/search.png'),
    CLEAR: require('../assets/icons/clear.png'),
    OPTION : require('../assets/icons/option.png'),
    BIRTHDAY: require('../assets/icons/birthday.png'),
    GENDER: require('../assets/icons/gender.png'),
    CAMERA: require('../assets/icons/camera.png'),
    GALLERY: require('../assets/icons/gallery.png'),
    WCAMERA: require('../assets/icons/w-camera.png'),
    WGALLERY: require('../assets/icons/w-gallery.png'),
    JOINEDAT: require('../assets/icons/joinat.png'),
    DONE: require('../assets/icons/done.png'),
    ARROW_RIGHT: require('../assets/icons/arrow_right.png'),
    AUTH_USERNAME :require('../assets/icons/auth_username.png'),
    AUTH_EMAIL :require('../assets/icons/auth_email.png'),
    AUTH_FULLNAME :require('../assets/icons/auth_fullname.png'),
    CARTS :require('../assets/icons/carts.png'),
    CARTS_ICON :require('../assets/icons/carts_icon.png'),
    BACK : require('../assets/icons/back.png'),
    INDICATOR : require('../assets/icons/indicator.png'),
    INDICATOR_IN : require('../assets/icons/indicator_in.png'),
    INDICATOR_OUT : require('../assets/icons/indicator_out.png'),
}