export default {
    BASE_URL : 'https://sydiary.herokuapp.com/',
    //BASE_URL : 'http://192.168.1.9:8080/',
    ACCESS_TOKEN_FROM_STORAGE    :   'access_token_from_storage',
    REFRESH_TOKEN_FROM_STORAGE  :   'refresh_token_from_storage',
    REMEMBER_STATE : 'remember_state',
    USERNAME_STORAGE : 'username_storage',
    FULLNAME_STORAGE:   'fullname_storage',
    GENDER_STORAGE : 'gender_storage',
    JOINEDAT_STORAGE:'joinedat_storage',
    SAFE_SEARCH_SETTING: 'safe_search_setting',
    EMAIL_STORAGE:  'email_storage',
    AVATAR_STORAGE:  'avatar_storage',
    USERID_STORAGE: 'userid_storage',
    BIRTHDAY_STORAGE:'birthday_storage',
    USERNAME_REMEMBER : 'username',
    PASSWORD_REMEMBER : 'password',
    

    BACK:   'Back',
    GO  :   'Go',
    SIGNUP: 'Sign up',
    SIGNIN: 'Sign in',
    WCBACK: 'Welcome \nBack',
    CRACCOUNT:  'Create \nAccount',
    ACCOUNTINFO: 'Account infomation',
    FULLNAME:'Full name',
    EMAIL:'Email address',
    USERNAME:'Username',
    PASSWORD:'Password',
    CPASSWORD:'Confirm password',
    REMEMBER:'Remember me',
    NOTHAVEACCOUNT : 'Not have an account? Join now!',
    HAVEACCOUNT:    'Have an account? Login now!',
    CHANGEPW:   'Password change',
    PREESSADDNEW: 'Press to add new diary',
    NODIARY:    'No diary to show',
    SYDIARY:    'Sync diary',
    NEWDIARY: 'New Diary',
    TITLE: 'Title in here',
    CONTENT: 'How was your day ?',
    SAVE:   'Save',
    CANCEL: 'Cancel',
    EDIT:   'Edit',
    DELETE: 'Delete',
    ISNEWDIARY: 'isNewDiary',
    AUTHENHEADER:'Welcome to SYDIARY',
    UPDATEPW : 'Update password',
    NEWPW: 'New password',
    CNEWPW: 'Confirm new password',
    DONE:   'Done',
    PWUPDATEDWARN:'Your password has been changed successfully.\nPlease login again with new password.',
    AGREE:'Agree',
    CONFIRMSIGNOUT:'Are you want to sign out ?',
    EDITDIARY:'Edit Diary',
    SEARCHING:'Searching',
    SELECT_NEW_IMAGE:'Select new profile image',
    SELECT_FROM_GALLERY:'From gallery',
    TAKE_FROM_CAMERA:'From camera',
    UPLOAD:'Upload',
    UPLOAD_THIS_IMAGE:'Upload this image',
    MALE:'Male',
    FEMALE:'Female',
    GENDER:'Gender',
    BIRTHDAY:'Birthday',
    JOINEDAT:'Joined at',
    PRIVACY:'Privacy',
    USER_PROFILE:'Profile',

    DESC_ACCOUNTINFO :'Update and modify your profile',
    DESC_CHANGEPW   :'Change your password',


    BRAND : ['Logitech','Cooler Master','Corsair','Fuhlen','Apple','Razer','DareU','Xiaomi','Microsoft'],
    BUYNOW: 'Buy now',
    CONTACT : 'Contact',
    OUTOFSTOCK : 'Out of stock',
}